name: Generate Podcast Feeds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Feed Generator Test
        uses: vinaykr0605/podcast-generator-test@main
